/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cassel.nosql;

import com.mongodb.ConnectionString;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoClient;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        
        for(int i = 0 ; i < args.length ; i++)
        {
        	if (args[i].equals("--db"))
        	{
                if (i + 1 < args.length && !args[i + 1].startsWith("--"))
                {
                  String database = args[i+1];
                }
                else
                {
                  throw new Exception("--db not defined");
                }
            }
        }
        
        MongoClient mongoClient = MongoClients.create();
        
        /*MongoDatabase database = mongoClient.getDatabase("mydb");
        MongoCollection<Document> collection = database.getCollection("test");

        Document myDoc = collection.find();
        System.out.println(myDoc.toJson());*/
    }
}
